Repository ryushin01/goobne, pull requests merged in 2023-12, with the labels that each got.

#8 📝 샘플 컴포넌트 업데이트
  src/components/Button/SampleButton.jsx
Labels: 리뷰 요청

#4 :lipstick:Component/button
  src/Router.jsx
  src/components/Button/Button.jsx
  src/styles/theme.jsx
Labels: 리뷰 반영 완료

#5 :lipstick: 아이콘 공용버튼컴포넌트 작업완료
  src/components/IconButton/IconButton.jsx
  src/svg/FooterBlogIconBtn.svg
  src/svg/FooterFacebookIcon.svg
  src/svg/FooterInstagramIcon.svg
  src/svg/FooterYouTubeIcon.svg
  src/svg/GlobalCartIconBtn.svg
  src/svg/GlobalCloseIconBtn.svg
  src/svg/HeaderListIconBtn.svg
Labels: 리뷰 반영 완료

#6 💄 Component/header 1차 PR 요청
  README.md
  public/images/HeaderCursorIcon.png
  public/images/logo.png
  src/components/Header/Header.jsx
  src/svg/Header/HeaderCursorIcon.svg
  src/svg/Header/HeaderMenuIcon.svg
  src/svg/Header/HeaderMenuSearchIcon.svg
  src/svg/Header/HeaderStoreIcon.svg
Labels: 리뷰 완료

#2 Footer HTML작업 완료, 공통 style추가 및 적용
  src/Router.jsx
  src/components/Footer/Footer.jsx
  src/styles/theme.jsx
Labels: 리뷰 반영 완료

#9 :ambulance:아이콘 버튼 색상,사이즈 변경불과 오류 수정
  src/components/IconButton/IconButton.jsx
Labels: 리뷰 반영 완료

#11 Fix/header
  src/components/Header/Header.jsx
Labels: 리뷰 요청

#13 :lipstick::art: 아이콘버튼 컬러 및 사이즈 적용, Address font 적용 및 :after 세로줄 위치조정
  src/components/Footer/Footer.jsx
Labels: 리뷰 요청

#15 ✨ Component/bigbanner 1차 PR 요청
  package-lock.json
  package.json
  public/data/BigBannerData.json
  public/images/main_banner_01.jpg
  public/images/main_banner_02.jpg
  public/images/main_banner_03.jpg
  public/images/main_banner_04.jpg
  src/API/API.jsx
  src/components/Badge/Badge.jsx
  src/components/BigBanner/BigBanner.jsx
  src/components/Header/Header.jsx
Labels: 리뷰 완료

#17 📦️ Github 배포를 위한 패키지(gh-pages) 설치
  package-lock.json
  package.json
Labels: 리뷰 요청

#16 component/checkbox
  src/components/Checkbox/Checkbox.jsx
Labels: 리뷰 반영 완료

#18 ✨ Component/selectbox 2차 PR 요청
  public/images/logo.png
  src/components/Header/Header.jsx
  src/components/SelectBox/SelectBox.jsx
Labels: 리뷰 반영 완료

#19 :lipstick: 라디오 컴포넌트 생성 및 1차 PR
  src/Router.jsx
  src/components/Radio/Radio.jsx
Labels: 리뷰 요청

#20 :art: 라디오버튼그룹화, 상수데이터 생성, map함수 데이터 연결확인
  src/components/Radio/Radio.jsx
  src/components/RadioGroup/RadioGroup.jsx
  src/data/RadioGroupData.jsx
Labels: 리뷰 요청

#12 :lipstick:Component/nav
  public/data/NavListData.json
  public/images/banner.png
  src/API/API.jsx
  src/Router.jsx
  src/components/Button/Button.jsx
  src/components/Header/Header.jsx
  src/components/IconButton/IconButton.jsx
  src/components/Nav/Nav.jsx
  src/svg/NavDownArrow.svg
  src/svg/NavUpArrow.svg
Labels: PR 완료

#14 Component/modal
  index.html
  src/components/Modal/Modal.jsx
  src/components/Modal/Portal.jsx
  src/components/Modal/Test.jsx
  src/components/Modal/TestComponent.jsx
  src/svg/ModalClose.svg
Labels: 리뷰 반영 완료

#22 fix/checkbox
  src/components/Checkbox/Checkbox.jsx
Labels: 리뷰 요청

#21 :art: 💄Component/input 컴포넌트 생성 및 UI적용
  src/Router.jsx
  src/components/Input/Input.jsx
Labels: 리뷰 요청

#23 :ambulance: footerContainer margin값제거
  src/components/Footer/Footer.jsx
Labels: PR 완료

#25 🎨 Header Scroll 이벤트 관련 로직 수정
  src/components/Header/Header.jsx
Labels: 리뷰 요청

#27 🚑️ Fix/swiper
  public/data/GoobNewsData.json
  public/data/MainBandData.json
  public/images/main-pizza.jpg
  public/images/main_beer.jpg
  public/images/main_chicken_01.jpg
  public/images/main_chicken_02.jpg
  public/images/main_chicken_03.jpg
  public/images/main_salad.jpg
  public/images/main_side_dish.jpg
  public/images/main_wast_set.jpg
  src/API/API.jsx
  src/components/BigBanner/BigBanner.jsx
  src/components/Header/Header.jsx
  src/components/Swiper/Band.jsx
  src/components/goobNews/GoobNews.jsx
  src/pages/Main.jsx
  src/styles/GlobalStyle.jsx
  src/styles/theme.jsx
Labels: 리뷰 요청

#31 ✨ Component/goobnews 1차 PR 요청
  public/data/GoobNewsData.json
  src/components/goobNews/GoobNews.jsx
Labels: 리뷰 반영 완료

#32 🚑️ Fix/api
  README.md
  src/components/BigBanner/BigBanner.jsx
  src/components/Swiper/Band.jsx
  src/components/goobNews/GoobNews.jsx
  src/config.jsx
Labels: 리뷰 요청

#28 :lipstick:로그인 페이지 UI 작업 완료 PR요청
  public/images/couponBanner.png
  src/Router.jsx
  src/components/Button/Button.jsx
  src/components/IconButton/IconButton.jsx
  src/components/Input/Input.jsx
  src/components/Nav/Nav.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/components/MemberLogin.jsx
  src/pages/Login/components/NonMemberLogin.jsx
  src/styles/theme.jsx
  src/svg/GlobalKaKaoIconBtn.svg
Labels: 리뷰 반영 완료

#29 💄 주문방법선택 페이지 UI 1차 PR
  src/Router.jsx
  src/pages/Delivery/Components/OrderMethod.jsx
  src/pages/Delivery/Delivery.jsx
Labels: 리뷰 반영 완료

#33 🎨 Fix/goobnews
  README.md
  src/components/goobNews/GoobNews.jsx
Labels: 리뷰 요청

#34 :lipstick: 페이지 여백 및 배경색, 버튼 이름 수정
  src/pages/Delivery/Delivery.jsx
Labels: 리뷰 반영 완료

#26 :lipstick: css속성 수정(디폴트인풋 bg컬러수정, label margin-bottom 값추가)
  src/components/Input/Input.jsx
Labels: 리뷰 반영 완료

#35 🚑️ Fix/selectbox 색상 및 size 변경
  src/components/SelectBox/SelectBox.jsx
Labels: 리뷰 요청

#36 :ambulance: 저해상도시 UI깨짐현상으로 인한 min-width지정 및 a링크 무효화 적용
  src/components/Footer/Footer.jsx
Labels: 리뷰 요청

#37 :ambulance: 인풋 테마컬러 적용, label 고정 width값 삭제
  src/components/Input/Input.jsx
Labels: 리뷰 요청

#38 ✨ Component/goobster 1차 PR 요청
  public/data/GoobStarData.json
  src/components/BigBanner/BigBanner.jsx
  src/components/goobNews/GoobNews.jsx
  src/components/goobStar/GoobStar.jsx
  src/config.jsx
  src/svg/Main/MainInstar.svg
Labels: 리뷰 요청

#39 🚑️ Fix/organize folder1st 폴더 정리
  src/components/IconButton/IconButton.jsx
  src/pages/Main.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/components/Band.jsx
  src/pages/Main/components/BigBanner.jsx
  src/pages/Main/components/GoobNews.jsx
  src/pages/Main/components/GoobStar.jsx
  src/svg/Footer/FooterBlogIconBtn.svg
  src/svg/Footer/FooterFacebookIcon.svg
  src/svg/Footer/FooterInstagramIcon.svg
  src/svg/Footer/FooterYouTubeIcon.svg
  src/svg/Global/GlobalCartIconBtn.svg
  src/svg/Global/GlobalCloseIconBtn.svg
  src/svg/Global/GlobalKaKaoIconBtn.svg
  src/svg/Header/HeaderListIconBtn.svg
  src/svg/Modal/ModalClose.svg
  src/svg/Nav/NavDownArrow.svg
  src/svg/Nav/NavUpArrow.svg
Labels: 리뷰 요청

#41 :ambulance::lipstick: background-color 이전속성 롤백
  src/components/Input/Input.jsx
Labels: 리뷰 요청

#42 🚑️🎨 Header Component 수정
  src/components/Header/Header.jsx
Labels: 리뷰 요청

#40 :lipstick:UI/join
  src/Router.jsx
  src/components/Input/Input.jsx
  src/components/Nav/Nav.jsx
  src/components/SelectBox/SelectBox.jsx
  src/config.jsx
  src/pages/Join/Join.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/components/MemberLogin.jsx
  src/pages/Login/components/NonMemberLogin.jsx
Labels: 리뷰 요청

#44 :lipstick:Feat/joinbase
  src/pages/BaseJoin/BaseJoin.jsx
  src/pages/BaseJoin/components/KakaoBtn.jsx
Labels: 리뷰 요청

#45 ✨ Component/goobtube 1차 PR 요청
  public/data/GoobTubeData.json
  public/images/PartnersLogo1.png
  public/images/PartnersLogo2.png
  src/config.jsx
  src/pages/Main/components/Goobtube.jsx
Labels: 리뷰 요청

#46 💄 Main 페이지 UI 1차 PR
  src/pages/Main.jsx
Labels: 리뷰 요청

#49 🚑️ Fix/axios api API 코드 개선 (원복)
  src/API/API.jsx
  src/config.jsx
  src/pages/Main.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/components/Band.jsx
  src/pages/Main/components/BigBanner.jsx
  src/pages/Main/components/GoobNews.jsx
  src/pages/Main/components/GoobStar.jsx
  src/pages/Main/components/Goobtube.jsx
Labels: 리뷰 요청

#47 :lipstick: 주문페이지 UI 생성 1차PR
  src/Router.jsx
  src/pages/Order/Order.jsx
  src/styles/theme.jsx
Labels: 리뷰 요청, 리뷰 반영 완료

#54 🎨 Fix/band 수정
  src/components/Badge/Badge.jsx
  src/components/Count/Count.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Main/components/OverMenu.jsx
Labels: 리뷰 요청

#55 :lipstick:로그인 페이지 기능개발
  src/API/API.jsx
  src/API/index.js
  src/Router.jsx
  src/pages/Login/components/MemberLogin.jsx
  src/pages/Login/components/NonMemberLogin.jsx
Labels: 리뷰 요청

#57 🎨 Fix/main 메인페이지 컴포넌트 관련 수정
  src/config.jsx
  src/pages/Main/components/GoobNews.jsx
  src/pages/Main/components/Goobtube.jsx
  src/pages/Main/components/OvenMenu.jsx
Labels: 리뷰 요청

#52 :art: 칩 컴포넌트 1차 PR
  src/components/Chip/Chip.jsx
Labels: 리뷰 요청

#59 Test/cart
  public/data/CartSwiper.json
  public/images/ProductDeleteButton.png
  src/Router.jsx
  src/config.jsx
  src/pages/Cart/Cart.jsx
  src/pages/Cart/Components/CartSwiper.jsx
  src/pages/Cart/Components/OrderDetail.jsx
  src/pages/Cart/Components/OrderInfo.jsx
  src/pages/Cart/Components/OrderProduct.jsx
  src/svg/Cart/arrow-left-short.svg
  src/svg/Cart/arrow-right-short.svg
Labels: 리뷰 요청

#61 Test/delivery
  public/data/DeliverySwiper.json
  public/images/CartSwiper_1.jpg
  public/images/CartSwiper_2.jpg
  public/images/CartSwiper_3.jpg
  src/config.jsx
  src/pages/Delivery/Components/DeliverySwiper.jsx
  src/pages/Delivery/Delivery.jsx
  src/pages/Main/Main.jsx
  vite.config.js.timestamp-1702948997736-a06eea864dcd6.mjs
Labels: 리뷰 요청

#56 :lipstick: 주문방법선택 상단 배너 추가
  public/images/CartSwiper_1.jpg
  public/images/CartSwiper_2.jpg
  public/images/CartSwiper_3.jpg
  src/pages/Delivery/Components/DeliverySwiper.jsx
  src/pages/Delivery/Delivery.jsx
Labels: 리뷰 완료

#60 ✨ Componets/dropdown UI 개발 완료
  README.md
  src/components/DropDown/Contents/ConutryOrigin.jsx
  src/components/DropDown/Contents/Nutrient.jsx
  src/components/DropDown/DropDown.jsx
Labels: 리뷰 반영 완료

#64 :lipstick:Feat/joinpage //회원가입 기능개발 PR
  package-lock.json
  package.json
  src/API/API.jsx
  src/API/TEST_API.js
  src/API/index.js
  src/Router.jsx
  src/components/Checkbox/Checkbox.jsx
  src/components/Footer/Footer.jsx
  src/components/Input/Input.jsx
  src/components/Nav/Nav.jsx
  src/components/ScrollTop/ScrollTop.js
  src/components/SelectBox/SelectBox.jsx
  src/config.jsx
  src/data/BirthData.jsx
  src/data/EmailData.jsx
  src/data/EventReceptionData.jsx
  src/data/RadioGroupData.jsx
  src/pages/Join/Join.jsx
  src/pages/Join/components/AdditionalInfo.jsx
  src/pages/Join/components/AgreementInfo.jsx
  src/pages/Join/components/BasicInfo.jsx
  src/pages/Join/components/PostModal.jsx
  src/pages/Join/components/RecommenderInfo.jsx
  src/pages/List/List.jsx
  src/pages/List/components/ListItem.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/components/MemberLogin.jsx
  src/pages/Login/components/NonMemberLogin.jsx
  src/pages/Main/components/BigBanner.jsx
  src/styles/GlobalStyle.jsx
Labels: 리뷰 반영 완료

#63 ⚡️ Feat/detail 디테일 페이지 2차 기능 추가 (라디오 버튼 선택에 따른 데이터 변경)
  public/data/DetailData.json
  src/components/Count/Count.jsx
  src/components/DropDown/Contents/ConutryOrigin.jsx
  src/components/DropDown/Contents/Nutrient.jsx
  src/components/DropDown/DropDown.jsx
  src/config.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/components/ButtonGroup.jsx
  src/pages/Detail/components/CustomRadio.jsx
  src/pages/Detail/components/RadioGroup.jsx
Labels: 리뷰 요청

#62 💄 장바구니 상품 수평 정렬 추가
  public/data/CartInfoData.json
  public/data/CartProductData.json
  src/config.jsx
  src/pages/Cart/Components/CartSwiper.jsx
  src/pages/Cart/Components/OrderDetail.jsx
  src/pages/Cart/Components/OrderInfo.jsx
  src/pages/Cart/Components/OrderProduct.jsx
Labels: 리뷰 반영 완료

#65 🎨 Feat/header 헤더 기능 추가
  src/components/Header/Header.jsx
  src/components/Nav/Nav.jsx
  src/pages/Login/components/MemberLogin.jsx
  src/pages/Login/components/NonMemberLogin.jsx
  src/svg/Header/HeaderCartIcon.svg
Labels: 리뷰 요청

#66 :lipstick:Feat/listpage 기능 PR
  public/data/ListItemAll.json
  public/data/ListItemBeer.json
  public/data/ListItemChicken.json
  public/data/ListItemData.json
  public/data/ListItemPizza.json
  public/data/ListItemSide.json
  public/data/MenuChipData.json
  public/data/TestData.json
  src/API/TEST_API.js
  src/components/Chip/MenuChipGroup.jsx
  src/config.jsx
  src/pages/List/List.jsx
  src/pages/List/components/ItemComponent.jsx
  src/pages/List/components/ListItem.jsx
Labels: 리뷰 반영 완료

#67 ♻️ Feat/detail 2 2차 PR 요청
  public/data/DetailData.json
  src/API/API.jsx
  src/API/TEST_API.js
  src/Router.jsx
  src/components/DropDown/Contents/Nutrient.jsx
  src/components/DropDown/DropDown.jsx
  src/components/Header/Header.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/components/CustomRadio.jsx
  src/pages/Detail/components/RadioGroup.jsx
  src/pages/Main/components/BigBanner.jsx
Labels: 리뷰 완료

#68 🎨 Feat/cart 2 2차 PR 요청
  package-lock.json
  package.json
  public/data/ListItemAll.json
  src/App.jsx
  src/Redux/Redux.jsx
  src/components/Count/Count.jsx
  src/components/Header/Header.jsx
  src/pages/Cart/Components/CartCount.jsx
  src/pages/Cart/Components/OrderDetail.jsx
  src/pages/Cart/Components/OrderProduct.jsx
  src/pages/Detail/Detail.jsx
  src/pages/List/List.jsx
Labels: 리뷰 반영 완료

#69 Feat/order 2차PR
  public/data/OrderData.json
  src/components/SelectBox/SelectBox.jsx
  src/config.jsx
  src/data/CouponData.jsx
  src/data/OrderRiderSelectBoxData.jsx
  src/data/OrderSelectBoxData.jsx
  src/data/PaymentMethodListData.jsx
  src/pages/Join/components/AdditionalInfo.jsx
  src/pages/Join/components/BasicInfo.jsx
  src/pages/Order/Order.jsx
  src/pages/Order/components/PaymentMethodList.jsx
  src/pages/Order/components/PaymentMethodListGroup.jsx
  src/svg/PaymentList/CreditCard.svg
  src/svg/PaymentList/KakaoPay.svg
  src/svg/PaymentList/NaverPay.svg
  src/svg/PaymentList/Payco.svg
  src/svg/PaymentList/PostPaidCard.svg
  src/svg/PaymentList/PostPaidCash.svg
Labels: 리뷰 반영 완료

#71 ⚡️ Fix main 2 메인페이지 수정 관련 1차 PR 요청
  public/images/MainModalGif.gif
  src/Redux/Redux.jsx
  src/components/Header/Header.jsx
  src/components/Modal/MainModalContent.jsx
  src/components/Modal/Modal.jsx
  src/pages/Cart/Components/OrderDetail.jsx
  src/pages/Delivery/Components/CustomRadio.jsx
  src/pages/Delivery/Components/OrderMethod.jsx
  src/pages/Delivery/Delivery.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/components/BigBanner.jsx
  src/pages/Main/components/OvenMenu.jsx
  src/styles/GlobalStyle.jsx
Labels: 리뷰 완료

#72 :lipstick:Fix/listpage
  public/data/ListItemAll.json
  public/data/ListItemBeer.json
  public/data/ListItemChicken.json
  public/data/ListItemPizza.json
  public/data/ListItemSide.json
  public/data/Loding.json
  src/components/Modal/DetailSelectModal.jsx
  src/components/Nav/Nav.jsx
  src/components/SelectBox/SelectBox.jsx
  src/pages/Cart/Components/OrderDetail.jsx
  src/pages/List/List.jsx
  src/pages/List/components/ItemComponent.jsx
Labels: 리뷰 반영 완료

#74 🩹 간단한 에러 수정
  README.md
  src/pages/Cart/Components/OrderInfo.jsx
  src/pages/Login/components/MemberLogin.jsx
  src/pages/Main/Main.jsx
Labels: 리뷰 요청

#75 :ambulance:Fix/minor
  package-lock.json
  package.json
  public/data/Loading.json
  public/data/Loding.json
  public/data/NavListData.json
  src/API/TEST_API.js
  src/components/Chip/MenuChipGroup.jsx
  src/components/Chip/PopularChipGroup.jsx
  src/components/DropDown/Contents/Nutrient.jsx
  src/components/DropDown/DropDown.jsx
  src/components/Loading/Loading.jsx
  src/components/LottieComponents/LottieComponents.jsx
  src/components/Nav/Nav.jsx
  src/components/SelectBox/SelectBox.jsx
  src/index.jsx
  src/pages/Cart/Components/CartSwiper.jsx
  src/pages/Cart/Components/OrderDetail.jsx
  src/pages/Delivery/Components/DeliverySwiper.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Detail/components/RadioGroup.jsx
  src/pages/Join/Join.jsx
  src/pages/Join/components/AgreementInfo.jsx
  src/pages/Join/components/BasicInfo.jsx
  src/pages/List/List.jsx
  src/pages/Login/components/MemberLogin.jsx
  src/pages/Login/components/NonMemberLogin.jsx
  src/pages/Main/components/BigBanner.jsx
  src/pages/Main/components/GoobNews.jsx
  src/pages/Main/components/GoobStar.jsx
  src/pages/Main/components/Goobtube.jsx
  src/pages/Main/components/OvenMenu.jsx
  src/pages/Order/Order.jsx
  vite.config.js.timestamp-1702948997736-a06eea864dcd6.mjs
Labels: 리뷰 요청

#77 :art::lipstick: 이용약관, 개인정보처리방침, 이메일무단수집거부 Modal생성및 컨텐츠내용작성
  src/components/Footer/Footer.jsx
  src/components/Modal/FooterEmailRefusal.jsx
  src/components/Modal/FooterTerms.jsx
  src/components/Modal/FooterUserInfo.jsx
Labels: 리뷰 요청

#70 :art: GET데이터(유저정보, 매장정보)생성 PR
  src/pages/Order/Order.jsx
Labels: 리뷰 요청

#79 :bug: QA-8 이슈해결
  src/components/Footer/Footer.jsx
Labels: 리뷰 요청

#80 ♻️ QA/Header Component 25번 해결
  src/components/Header/Header.jsx
Labels: 리뷰 요청

#81 :ambulance:[QA-24] 사이드 네비게이션에서 회원 이름 미노출 이슈
  src/components/Nav/Nav.jsx
Labels: 리뷰 요청

#82 ♻️ QA/Header Component 1번 해결
  src/components/Header/Header.jsx
Labels: 리뷰 요청

#83 ♻️ QA/header 10번 해결
  src/components/Header/Header.jsx
Labels: 리뷰 요청

#84 ♻️ QA/header 2번 임시 해결
  src/components/Header/Header.jsx
Labels: 리뷰 요청

#87 ✏️ 리드미 수정 , QA 2번 재 수정
  README.md
  src/components/Header/Header.jsx
Labels: 리뷰 요청

#89 :ambulance:[QA-15] 회원가입 페이지의 디자인 이슈
  src/pages/Join/Join.jsx
  src/pages/Join/components/AdditionalInfo.jsx
Labels: 리뷰 반영 완료

#88 :ambulance:[QA-24] 메뉴보기 페이지의 포장전용 선택 불가
  public/data/MenuChipData.json
  public/images/notData.png
  src/pages/List/List.jsx
Labels: 리뷰 반영 완료

#90 ♻️ QA/main_4 BigBanner 커서 아이콘 추가
  public/images/banner-cursor.png
  src/pages/Main/components/BigBanner.jsx
Labels: 리뷰 요청

#91 :ambulance:[QA-3] 사이드 네비게이션 디자인 상이
  src/components/Nav/Nav.jsx
Labels: 리뷰 반영 완료

#92 ♻️ QA/main_5 수정 완료
  public/data/MainBandData.json
Labels: 리뷰 요청

#86 :bug:QA-9 이슈해결
  src/components/Footer/Footer.jsx
Labels: 리뷰 요청

#93 ♻️ QA/main_6 번 해결
  public/data/GoobNewsData.json
  src/pages/Main/components/GoobNews.jsx
  src/pages/Main/components/GoobStar.jsx
  src/pages/Main/components/Goobtube.jsx
Labels: 리뷰 요청

#96 :ambulance:[QA-11] 메뉴보기 페이지 디자인 이슈
  src/components/Chip/Component/Chip.jsx
  src/pages/List/List.jsx
  src/pages/List/components/ItemComponent.jsx
Labels: 리뷰 반영 완료

#98 :ambulance:[QA-12] 메뉴보기 페이지의 첫 번째 아이템 디자인 이슈
  public/data/ListItemAll.json
  public/data/ListItemBeer.json
  public/data/ListItemChicken.json
  public/data/ListItemPizza.json
  public/data/ListItemSide.json
  public/images/beer17.png
  public/images/beer18.png
  public/images/beer19.png
  public/images/beer20.png
  public/images/beer21.png
  public/images/beer22.png
  public/images/chicken00.png
  public/images/chicken01.png
  public/images/chicken02.png
  public/images/chicken03.png
  public/images/chicken04.png
  public/images/chicken05.png
  public/images/pizza06.png
  public/images/pizza07.png
  public/images/pizza08.png
  public/images/pizza09.png
  public/images/pizza10.png
  public/images/pizza11.png
  public/images/side12.png
  public/images/side13.png
  public/images/side14.png
  public/images/side15.png
  public/images/side16.png
  public/images/side17.png
  public/images/testimg.png
  src/pages/List/List.jsx
  src/pages/List/components/ItemComponent.jsx
Labels: 리뷰 반영 완료

#95 ♻️ QA/detail_14 이슈 해결
  src/components/DropDown/Contents/Nutrient.jsx
Labels: 리뷰 요청

#100 :bug: QA-18 이슈해결
  src/pages/Order/Order.jsx
Labels: 리뷰 요청

#94 :bug: QA-19 이슈해결(컴포넌트담당자협의 옵션선택창 색상변경)
  src/components/SelectBox/SelectBox.jsx
Labels: 리뷰 요청

#97 🐛 QA-20 이슈해결
  src/components/Modal/OrderAmountModal.jsx
  src/pages/Order/Order.jsx
Labels: 리뷰 요청

#103 Test/cart swiper 아이템, 텍스트 클릭시 동적라우팅구현
  public/data/CartSwiper.json
  src/pages/Cart/Components/CartSwiper.jsx
Labels: 리뷰 요청

#104 📝 디테일 데이터 수정
  public/data/DetailData.json
Labels: 리뷰 요청

#105 :ambulance: 디테일페이지 swiper 이미지 변경
  public/data/DeliverySwiper.json
  public/images/CartSwiper_1.jpg
  public/images/CartSwiper_2.jpg
  public/images/CartSwiper_3.jpg
  public/images/CartSwiper_4.jpg
Labels: 리뷰 요청

#102 🚧 빅배너 이미지 클릭 시 list 페이지로 이동 하도록 경로 추가 + 이미지 변경
  public/data/BigBannerData.json
  public/images/main_banner_01.jpg
  public/images/main_banner_02.jpg
  public/images/main_banner_03.jpg
Labels: 리뷰 요청

#106 🚑️ Detail 페이지 이미지 변경 및 데이터 수정, ovenMenu 데이터 수정
  public/data/DetailData.json
  public/data/MainBandData.json
  public/images/chicken00_1.png
  public/images/chicken00_2.png
  src/pages/Detail/Detail.jsx
Labels: 리뷰 요청

#107 ♻️ 마지막 리펙토링 코드 커밋
  public/data/BigBannerData.json
  public/images/main_banner_04.jpg
  src/pages/Cart/Components/OrderDetail.jsx
  src/pages/Detail/Detail.jsx
  src/pages/Main/components/BigBanner.jsx
  src/pages/Order/Order.jsx
Labels: 리뷰 요청

#109 Fix/hotfix
  public/images/NavDownArrow.svg
  public/images/NavUpArrow.svg
  src/components/Nav/Nav.jsx
Labels: PR 완료

#110 🚑️ 파비콘 추가, goobnews height -> min-height 로 수정
  index.html
  public/favicon/android-icon-144x144.png
  public/favicon/android-icon-192x192.png
  public/favicon/android-icon-36x36.png
  public/favicon/android-icon-48x48.png
  public/favicon/android-icon-72x72.png
  public/favicon/android-icon-96x96.png
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/apple-icon-precomposed.png
  public/favicon/apple-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/manifest.json
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
  src/pages/Main/components/GoobNews.jsx
Labels: 리뷰 요청

#111 Hotfix/order
  public/images/Footer/FooterBlogIconBtn.svg
  public/images/Footer/FooterFacebookIcon.svg
  public/images/Footer/FooterInstagramIcon.svg
  public/images/Footer/FooterYouTubeIcon.svg
  public/images/Nav/NavDownArrow.svg
  public/images/Nav/NavUpArrow.svg
  public/images/PaymentList/CreditCard.svg
  public/images/PaymentList/KakaoPay.svg
  public/images/PaymentList/NaverPay.svg
  public/images/PaymentList/Payco.svg
  public/images/PaymentList/PostPaidCard.svg
  public/images/PaymentList/PostPaidCash.svg
  src/components/Nav/Nav.jsx
  src/data/PaymentMethodListData.jsx
  src/pages/Order/Order.jsx
Labels: 리뷰 요청

#112 이미지 절대경로로 수정
  public/data/DeliverySwiper.json
  src/pages/List/List.jsx
Labels: PR 완료

#113 딜리버리 스와이퍼 절대경로 수정
  public/data/DeliverySwiper.json
Labels: 리뷰 요청

#115 🚑️ 개별 삭제 icon 경로 수정
  src/pages/Cart/Components/OrderProduct.jsx
Labels: 리뷰 요청

#116 장바구니 swiper 화살표 경로수정
  public/images/Cart/arrow-left-short.svg
  public/images/Cart/arrow-right-short.svg
  src/pages/Cart/Components/CartSwiper.jsx
  src/svg/Nav/NavDownArrow.svg
  src/svg/Nav/NavUpArrow.svg
  src/svg/PaymentList/CreditCard.svg
  src/svg/PaymentList/KakaoPay.svg
  src/svg/PaymentList/NaverPay.svg
  src/svg/PaymentList/Payco.svg
  src/svg/PaymentList/PostPaidCard.svg
  src/svg/PaymentList/PostPaidCash.svg
Labels: 리뷰 요청

#118 카트 swiper 화살표 UI수정
  src/pages/Cart/Components/CartSwiper.jsx
Labels: 리뷰 요청

#119 🚑️ 디테일 페이지 이미지 속성 변경
  src/pages/Detail/Detail.jsx
Labels: 리뷰 요청
